# Use pre-built docker containers to run our unit tests on different python versions.

name:  Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      python-version: [3.6, 3.7, 3.8]
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v2
    with:
      python-version: ${{ matrix.python-version }}
  - name: Install Dependencies
    run: ./test_scripts/install_deps_ubuntu.sh
  - name: Install Package
    run: pip3 install .
  - name: Run Tests
    run: python3 -c 'import pshmem; pshmem.test()'
